### ISSUE TITLE
FireArmamentPower lacks shared actor superweapon range.

### ISSUE THREAD

**Issue by ABrandau** [AttacqueSuperior/Engine#55]
Aka EMP Cannon shared range radius.

**Comment by GraionDilach** [comment]
What? Pretty sure TS didn't have such - if the target wasn't in range of a particular cannon from multiple instances, that instance could not fire.

**Comment by ABrandau** [comment]
Yeah, thats correct, having multiple EMP cannons would only extend its firing radius, a while ago I tested your trait to replace AttackOrder power, so i build a pair of cannons, and when i selected the superweapon, only the first cannon would draw a radius, so it doesnt consider the range of the other instances.

**Comment by ABrandau** [comment]
Ok, following your advice, I went with this, it still doesnt replicate the TS behaviour 1:1 because it will order all EMP cannons in range to fire, but it is good enough for SP, thanks!

```
FireArmamentPower:
        AllowMultiple: False
        Cursor: emp
        MaximumFiringInstances: 1000
        ArmamentName: primary
        Icon: emp
        ChargeInterval: 3000
        Description: E.M. Pulse
        LongDesc: Fires a pulse blast which disables\nall mechanical units in the area.
        EndChargeSound: speech-nod|00-i158.aud
        SelectTargetSound: n_00-i042.aud
        Prerequisites: emp.gdi
        OrderName: Nodemp
        PauseOnCondition: disabled
```
